#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

// Set 0 - Shared UBO
layout(set = 0, binding = 0) uniform Matrices
{
    mat4 model;
    mat4 view;
    mat4 proj;
}
uMatrices;

// Set 2 - SSBO
layout(std430, set = 2, binding = 1) buffer DataBuffer
{
    float values[];
}
ssboData[];

// Set 2 - Storage Image
layout(set = 2, binding = 2, rgba32f) uniform image2D resultImage;

// Shared push constant
layout(push_constant) uniform PushConsts
{
    vec4 colorMod;
    float metallic;
    float roughness;
}
pushConsts;

void main()
{
    ivec2 id = ivec2(gl_GlobalInvocationID.xy);
    float factor = ssboData[0].values[id.x] * pushConsts.roughness;
    imageStore(resultImage, id, vec4(factor));
}
